### PR TITLE
Update Languages.cs

### PR DESCRIPTION
**Pull request by Jay-o-Way**
- Missing German "Eszett" https://en.wikipedia.org/wiki/%C3%9F under "All"
- Polish currency "złoty"
- https://en.wikipedia.org/wiki/Turkish_lira under "L"

### CODE REVIEW

**Comment by Jay-o-Way** [comment]
> can't see Polish & German modifications

Ah yes these are suggestions. You can add them the way you want to.

**Comment by damienleroy** [comment]
Oh ok ! :D 
Sure I will add them so. Thanks for the suggestion and the PR! :)

**Comment by damienleroy** [comment]
@Jay-o-Way 
FYI, can not implement Polish currency for now. This currency ask 2 characters. It is like characters asking 2 unicodes. I have some issues about that and for now the app is not construct for this. It is an upgrade I have to do to accepte them.
So for Polish currency currently it is 2 separate characters. And they are present.

**Comment by Jay-o-Way** [comment]
No problem

**Pull request merged**
