### PR TITLE
Additional languages DE, CZ, SK

### PR DESCRIPTION
**Pull request by Dugowitch**
Added languages: German (DE), Czech (CZ), Slovak (SK)

### CODE REVIEW

**Comment by damienleroy** [comment]
Hello, looks good. But you forgot to add images as ressources of the project.
I think it should be ok after that.

**Comment by Dugowitch** [comment]
Of course, hopefully it's all right now

**Comment by damienleroy** [comment]
Fixed some part in the csproj. Is it clearer and going well. If it's ok for you I will merge it.

**Comment by Dugowitch** [comment]
It's ok for me, go ahead

**Pull request merged**
