### PR TITLE
Add Pinyin (Chinese)

### PR DESCRIPTION
**Pull request by jmonticolo**
resolve a part of #94.

### CODE REVIEW

**Comment by damienleroy** [comment]
Hello, Pinyin was already added:
https://github.com/damienleroy/PowerAccent/blob/main/PowerAccent.Core/Languages.cs#L356-L376
But it look like different. Is it used by a different region may be?
I am thinking, may be it is better to modify the current existing Pinyin, to add missing characters

**Comment by jmonticolo** [comment]
I can't really answer ... I based my work on this section of Wikipedia page : https://en.wikipedia.org/wiki/Pinyin#Tones

**Comment by damienleroy** [comment]
It is not really usefull no. 
But I guess I see you're changes. The added letters on the U are in fact already implemented on th V.
The reason was originally from there:
https://github.com/damienleroy/PowerAccent/issues/10

**Comment by damienleroy** [comment]
So thank you to this, but I think we are already ok with Pinyin :)

**Pull request closed without merging**
